### ISSUE TITLE
Client Identity Validation Behavior

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/smart-launcher-v2#14]
@jmandel wrote:
> Now, playing with the sample app, I notice that even when I have enabled "App Registration Options" of "Client Identity Validation Method: client-confidential-asymmetric", the sample app is still able to get an access token without authenticating. Is this a bug in the token endpoint logic?

**Comment by vlad-ignatov** [comment]
Currently, the "Client Identity Validation" option is UI-only, meaning that it will hide or show the fields in which you could enter client secret or JWKS/JWKS-URL. This does not control if the app will actually use a secret or asymmetric auth. I might be able to make such a "connection" between the launcher options and the sample app, but all other apps will still do whatever they want.

In other words, it enables auth validation but cannot force apps to use that type of authentication. Do you have better ideas?

**Comment by vlad-ignatov** [comment]
This is just a mockup UI that I have locally. Before I attempt implementing it, do you thinks these options make sense (as well as the labels and descriptions)?

<img width="1161" alt="Screen Shot 2022-10-26 at 6 29 22 PM" src="https://user-images.githubusercontent.com/1119082/198150893-dd59d99d-d8c9-424f-84b0-9100b689a82a.png">

**Comment by jmandel** [comment]
Cool, thanks for sharing this mock up. The ability to get out of sync between the options registered on the registration tab and the options selected on the validation tab would worry me a little bit. Have you thought about whether it's possible to combine them in one screen, or even just to make the validation choices implicit based on which registration details are filled out? My assumption based on our initial prototype was that if you put a detail in your registration screen, you are asking to have it validated.

**Comment by vlad-ignatov** [comment]
> My assumption based on our initial prototype was that if you put a detail in your registration screen, you are asking to have it validated.

Correct, but it does not cover everything. I'll experiment with combining them...

**Comment by vlad-ignatov** [comment]
How about now (deployed)? These are big changes and I still need to clean up the code and tests, but I think it is a slight improvement.

**Comment by jmandel** [comment]
This is looking really good.

![image](https://user-images.githubusercontent.com/313089/198724700-c1e56160-d919-4a1c-91d3-9b13e2de08ec.png)

I'm thinking it might be more straightforward (and flexible) to allow piecemeal opt-in to the strict validation aspects. To this end, I wonder if it's possible to relax the "Loose" validation to say (and do) something like:

* Client ID is not validated (any well-formed value is allowed)
* Scopes are not validated (any well-formed value is allowed)
* Redirect URIs are not validated (any well-formed value is allowed)
* Client authentication is not validated (any well-formed value is allowed)

... and then turning on "strict" could provide metadata-driven behaviors like:

* If you provide a Client ID at registration time, your `client_id` at runtime must match
* If you provide Allowed Scopes at registration time, your `scope` at runtime must be covered by this set
* If you provide Allowed Redirect URIs at registration time your `redirect_uri` must be included in this set
* If you provide a JWKS or JWKS URL at registration time your client authentication assertion must be signed with a public key from this set

**Comment by vlad-ignatov** [comment]
This is close to what it does. Currently:

**Loose** is what we used to have. It makes all registration-time options optional, meaning that you can leave them empty to skip that part of the validation. If you do use them, they should be well-formed and should be used at runtime.

**Strict** goes a step further by requiring all the registration options to be set, so that we have something closer to the real-world launch with well-defined client.

So loose would be the piecemeal option but its description would be more like what you suggested for "strict". I'm not sure relaxing "loose" further would be useful. For example "Client ID is not validated (any well-formed value is allowed)" would mean that I should verify that that `client_id` is "well-formed" if present, even though I wouldn't use it at runtime...

**Comment by jmandel** [comment]
Hmm, this might be entirely a question of what's documented, so perhaps I'm just saying that I'm confused by the current wording.

When I read "Client ID can be empty to allow any client_id" I'm confused because:

1. We don't state what happens if Client ID is present
2. If I supply Client ID, it's treated identically between "loose" and "strict" modes

My suggested "flip" + language above avoids this confusion (for me at least -- perhaps you think it introduces *other* confusions, though).

**Comment by vlad-ignatov** [comment]
Yes, it is quite difficult to figure out the best wording. Note that we should probably avoid "at registration time" within this tab, otherwise some users might wonder where that is supposed to be... How about:

**Loose**
- If you provide a **Client ID**, your `client_id` at runtime must match
- If you provide **Allowed Scopes**, your `scope` at runtime must be covered by this set
- If you provide **Allowed Redirect URIs**, your `redirect_uri` must be included in this set
- If you provide a **JWKS** or **JWKS URL**, your client authentication assertion must be signed with a public key from this set
- If you provide a **Client Secret**, the `client_secret` in your authentication header must be the same

**Strict**
- You must provide a **Client ID** and your `client_id` at runtime must match
- You must provide **Allowed Scopes** and your `scope` at runtime must be covered by this set
- You must provide **Allowed Redirect URIs** and your `redirect_uri` must be included in this set
- You must provide a **JWKS** or **JWKS URL** and your client authentication assertion must be signed with a public key from this set
- You must provide a **Client Secret** and the `client_secret` in your authentication header must be the same


Another, more relaxed way to do this might be:

**Loose** - _hides all inputs and says:_
- Your app can use any `client_id`
- Your app can request any  `scope`
- Your app can use any `redirect_uri`
- Your app can use any structurally valid authentication assertion JWT
- Your app can use any `client_secret`

**Strict**
- If you provide a **Client ID**, your `client_id` at runtime must match
- If you provide **Allowed Scopes**, your `scope` at runtime must be covered by this set
- If you provide **Allowed Redirect URIs**, your `redirect_uri` must be included in this set
- If you provide a **JWKS** or **JWKS URL**, your client authentication assertion must be signed with a public key from this set
- If you provide a **Client Secret**, the `client_secret` in your authentication header must be the same

**Comment by jmandel** [comment]
Excellent -- both of these suggestions seem clear to me. I prefer the "more relaxed way" (aligns with https://github.com/smart-on-fhir/smart-launcher-v2/issues/14#issuecomment-1295431064)

**Comment by vlad-ignatov** [comment]
Well..., this was a tricky UI but I think I finally got it to work fine.
