### ISSUE TITLE
invalid_client: Invalid client details token: jwt malformed

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/smart-launcher-v2#15]
@jmandel wrote:
> I'm seeing this using the launcher with asymmetric auth. First, I tried using asymmetric auth without choosing any settings from the "App Registration Options" tab (after all, we say "All of these settings are optional"). Probably worth relaxing the client validation when no options are selected.

>  Next, I've selected "asymmetric auth" and pasted in a JWKS of 
  ```
  {
      "keys": [{
          "kty": "EC",
          "crv": "P-384",
          "x": "wcE8O55ro6aOuTf5Ty1k_IG4mTcuLiVercHouge1G5Ri-leevhev4uJzlHpi3U8r",
          "y": "mLRgz8Giu6XA_AqG8bywqbygShmd8jowflrdx0KQtM5X4s4aqDeCRfcpexykp3aI",
          "kid": "afb27c284f2d93959c18fa0320e32060",
          "alg": "ES384"
      }]
  }
  ```

> OK, so now I have chosen asymmetric auth and supplied a JWKS. Still getting the same error on the token endpoint when I try to authorize with the client at https://glitch.com/edit/#!/sharp-lake-word?path=standalone.html%3A18%3A0. The JWTs submitted are not, on their own, obviously invalid; here's an example:
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7Im5lZWRfcGF0aWVudF9iYW5uZXIiOnRydWUsInNtYXJ0X3N0eWxlX3VybCI6Imh0dHBzOi8vc21hcnQtbGF1bmNoZXItc3RhZ2luZy5oZXJva3VhcHAuY29tL3NtYXJ0LXN0eWxlLmpzb24iLCJwYXRpZW50IjoiNjdjYmYwOTAtNGRkYi00Nzk5LTk5ZmYtYTI4YWJlMjc0MGIxIn0sImNsaWVudF9pZCI6ImRlbW9fYXBwX3doYXRldmVyIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9zaGFycC1sYWtlLXdvcmQuZ2xpdGNoLm1lL2dyYXBoLmh0bWwiLCJzY29wZSI6ImxhdW5jaC9wYXRpZW50IHBhdGllbnQvT2JzZXJ2YXRpb24ucnMgcGF0aWVudC9QYXRpZW50LnJzIG9mZmxpbmVfYWNjZXNzIHBhdGllbnQvSW1hZ2luZ1N0dWR5LnJzIiwiY29kZV9jaGFsbGVuZ2VfbWV0aG9kIjoiUzI1NiIsImNvZGVfY2hhbGxlbmdlIjoiQ1BHZDlsWVB2Y0RGUUJBaUN3ODJLVGVHS0JBRmtkeEJjN1hkamcwaDktVSIsImp3a3MiOiJ7XCJrZXlzXCI6IFt7IFwia3R5XCI6IFwiRUNcIiwgXCJjcnZcIjogXCJQLTM4NFwiLCBcInhcIjogXCJ3Y0U4TzU1cm82YU91VGY1VHkxa19JRzRtVGN1TGlWZXJjSG91Z2UxRzVSaS1sZWV2aGV2NHVKemxIcGkzVThyXCIsIFwieVwiOiBcIm1MUmd6OEdpdTZYQV9BcUc4Ynl3cWJ5Z1NobWQ4am93ZmxyZHgwS1F0TTVYNHM0YXFEZUNSZmNwZXh5a3AzYUlcIiwgXCJraWRcIjogXCJhZmIyN2MyODRmMmQ5Mzk1OWMxOGZhMDMyMGUzMjA2MFwiLCBcImFsZ1wiOiBcIkVTMzg0XCJ9XSB9IiwiaWF0IjoxNjY2MDI1NjY0LCJleHAiOjE2NjYwMjU5NjR9.nj63235VbwQKc9beSucVJu_4rSX45xjf9oIgb1SpfHE
```

> I've tried also adding the Client ID (`"demo_app_whatever"`) and still get the same error.

> Reading the fine print I see "each JWK must have a kid property and a key_ops array that includes 'verify'" -- which I'm not sure is consistent with https://hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html (where we make no such claim). But I try adding this, so my JWKS now looks like 

```
{
    "keys": [{
        "kty": "EC",
        "crv": "P-384",
        "x": "wcE8O55ro6aOuTf5Ty1k_IG4mTcuLiVercHouge1G5Ri-leevhev4uJzlHpi3U8r",
        "y": "mLRgz8Giu6XA_AqG8bywqbygShmd8jowflrdx0KQtM5X4s4aqDeCRfcpexykp3aI",
        "kid": "afb27c284f2d93959c18fa0320e32060",
        "alg": "ES384",
        "key_ops": ["verify"]
    }]
}
```

> ... but still get the same error. So I'm stuck on this one.

**Comment by vlad-ignatov** [comment]
1. I fixed one error and I hope it works for you now?

2. `Probably worth relaxing the client validation when no options are selected` - The only possible relaxing here (which I've done now) is to make the **jwks url** optional. If that is set in the UI, it should match the `jku` header. Otherwise, I just fetch the JWKS from the `jwtHeader.jku` without checking that it matches the **jwks url** option. If `jku` is absent, then one must supply JWKS or JWKS URL in the registration options, or the auth would fail.

3. **All the registration options are optional** - turns out there is one exception which I am not sure how to handle (in UI/UX).
If you use asymmetric auth without JWKS URL (without `jku` header), then you **MUST** supply JWKS as json.

4. > Reading the fine print I see "each JWK must have a kid property and a key_ops array that includes 'verify'" -- which I'm not sure is consistent with https://hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html (where we make no such claim).
    
    Can't remember where I got that from, but the idea was to filter out the public keys from the JWKS (because in theory it can also contain private keys). However:
    - Some private keys can also be used for verification (AFAIK)
    - If a correct key is not found the auth would fail anyway
    - If the user hosts private keys that is an issue on their end, not ours

    That said, I have now removed the `key_ops` requirement

**Comment by jmandel** [comment]
(1) Confirmed, this is working now, thanks!

(2), (3) this makes sense. I was hitting a couple of stacked errors and it was hard for me to tell whether the "client id" field was contributing. I've now confirmed that I can leave "client id" blank in the registration screen and no validation is applied, thanks!

(4) Sounds good.
