### ISSUE TITLE
No .well-known endpoint for OpenID Connect

### ISSUE THREAD

**Issue by arscan** [smart-on-fhir/smart-launcher-v2#22]
It looks like this almost supports OpenID Connect (an id_token is provided with a valid Practitioner resource as a user), but it doesn't provide the `.well-known/openid-configuration` well-known endpoint to validate the id_token.  It is just rendering an html page there. Let me know if you think we are doing something wrong though.

https://inferno.healthit.gov/suites/test_sessions/5fb92232-ee6e-4cd1-942f-f3939839d66f#g10_certification-g10_smart_standalone_patient_app

![Screen Shot 2022-11-01 at 3 45 01 PM](https://user-images.githubusercontent.com/412901/199324521-186cef4f-ca69-4bab-8c92-35a951dff420.png)

This is a really nice improvement from v1, good job!

**Comment by vlad-ignatov** [comment]
Thanks @arscan,

I am trying to figure out why this is happening. The `.well-known/openid-configuration` is available at [{FhirBaseURL}/.well-known/openid-configuration](https://smart-launcher-staging.herokuapp.com/v/r4/sim/WzMsIiIsIiIsIkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMV0/fhir/.well-known/openid-configuration)

Looking at Inferno settings, I can see that **FHIR Endpoint** is defined as `https://smart-launcher-staging.herokuapp.com/v/r4/sim/......./fhir` but the openid config is expected at https://smart-launcher-staging.herokuapp.com/v/r4/sim/......./auth/fhir/.well-known/openid-configuration (note the extra `auth` segment). Do you have any idea how Inferno is building that URL?

**Comment by arscan** [comment]
It looks like the `iss` parameter in the decoded id_token has that extra `auth` segment.  Tests for SMART in Inferno are more like "steps", and you can see what gets passed between the steps by inspecting the `output` and `input` tabs.  In this case, you can see what the id_token gets decoded as in the '1.5.01 ID Token can be decoded' test and passed to later tests as an input:

![Screen Shot 2022-11-01 at 7 47 24 PM](https://user-images.githubusercontent.com/412901/199362883-534bb44b-2b3b-430a-a25c-8d41797c3c8f.png)

This is consistent with what the sample app that you provide says (which is *excellent* too!):
![Screen Shot 2022-11-01 at 7 55 53 PM](https://user-images.githubusercontent.com/412901/199363715-1efa039b-6125-4312-adb5-3af2cbb2e534.png)

Per the [SMART spec](http://hl7.org/fhir/smart-app-launch/scopes-and-launch-context.html#steps-for-using-an-id-token):

> 3.0.7 Steps for using an ID token
>    1. Examine the ID token for its “issuer” property
>    2. Perform a GET {issuer}/.well-known/openid-configuration
>    3. Fetch the server’s JSON Web Key by following the “jwks_uri” property
>    4. Validate the token’s signature against the public key from step #3
>    5. Extract the fhirUser claim and treat it as the URL of a FHIR resource

So we don't use the {fhirBaseURL} but instead we use {iss} here, as required by the spec.  I don't think that the spec says anywhere that the iss must equal the fhir base url, but if it did we could add that check here which might have been a more straightforward way to figure out what was wrong.

**Comment by vlad-ignatov** [comment]
Thanks Rob, this is a perfect explanation! I have that fixed, although I can't quite figure out how to test it with Inferno.

**Comment by arscan** [comment]
Closer, because now we can retrieve the well-known endpoint.  But that file (located at https://smart-launcher-staging.herokuapp.com/v/r4/sim/.../fhir/.well-known/openid-configuration) lists the 'issuer' as https://smart-launcher-staging.herokuapp.com/v/r4/fhir, but the id_token provides an iss value of https://smart-launcher-staging.herokuapp.com/v/r4/sim/.../fhir.  Those must match.

I think you need to update the issuer to include that `sim/...` in the case of standalone launches here:

https://github.com/smart-on-fhir/smart-launcher-v2/blob/f795eaf1c1e3f619bf510545e866e2956511eb01/backend/routes/fhir/.well-known/openid-configuration.ts#L15-L20

I also highlighted the comment above which helpfully points out that the issuer there must match the iss in the id_token, which is what our tests flag as an error.

You can see the error in [this inferno session](https://github.com/smart-on-fhir/smart-launcher-v2/blob/f795eaf1c1e3f619bf510545e866e2956511eb01/backend/routes/fhir/.well-known/openid-configuration.ts#L15-L20).  You can just click 'run tests' at the top right to rerun those tests.

There are also a few more fields in the well-known that it looks like you are supposed to fill out.

![Screen Shot 2022-11-02 at 9 33 33 AM](https://user-images.githubusercontent.com/412901/199503050-7a993a4d-e7c6-445b-bbe8-48a778713314.png)

Let me know if any of those errors don't look right to you.

**Comment by vlad-ignatov** [comment]
I think I got all those fixed, but now I'm getting an expired id token error. I definitely can't figure out how to use inferno to go through the auth flow and obtain new id_token.

**Comment by arscan** [comment]
Hmm, ok.  Clearly we need to improve the experience when just testing servers for SMART App Launch support, outside the g10 context.  We haven't focused much on that yet.

Regardless, those updates caused all our tests to pass against both our SMART App Launch v1 tests and SMART App Launch v2 tests. And it passed the Backend Services Authorization tests that we have as well.  👍

**Comment by vlad-ignatov** [comment]
Thank you! Even though the launcher is basically a faking tool, it is nice to know that it is faking things properly :)
