### ISSUE TITLE
system/ scopes should support query params

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-launcher-v2#31]
Just realized the system scope parsing will still prohibit things like `system/Observation.rs?category=laboratory`

**Comment by vlad-ignatov** [comment]
Do you mean that it should prohibit them (and if so - why?), or that it does but it shouldn't? How are you testing that?

**Comment by jmandel** [comment]
Oh, never mind me :-)

I already covered this in https://github.com/smart-on-fhir/smart-launcher-v2/pull/28/files#diff-1cf7339dde456d3977ddf866eb9de1c22be3e2c2d14e5a7893e3a6248961fd80R90
