### ISSUE TITLE
Wrong query parameters _format in PatientPicker

### ISSUE THREAD

**Issue by vpwang** [smart-on-fhir/smart-launcher-v2#37]
I found that the _fomat parameter is application/json+fhir in PatientPicker, which is correct in R2.
However, the rule has changed to support application/fhir+json instead of application/json+fhir since R3.

The latest R5 documentation https://hl7.org/fhir/R5/http.html#parameters also states that
"For the _format parameter, the values xml, text/xml, application/xml, and application/fhir+xml SHALL be interpreted to mean the [XML format](https://hl7.org/fhir/R5/xml.html), the codes json, application/json and application/fhir+json SHALL be interpreted to mean the [JSON format](https://hl7.org/fhir/R5/json.html)".

Though it's very easy to change the parameters in my local environment, I think it's better to remind you of this issue.

**Comment by vlad-ignatov** [comment]
Thank you! It should be fixed now.
