### ISSUE TITLE
Improve scope labels

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/smart-launcher-v2#7]
![image](https://user-images.githubusercontent.com/1119082/196503313-86d13fb4-eee0-4d71-85c8-2a6ad1012b10.png)

This description of "The current patient selection" isn't quite telling the whole story. Would suggest saying "read all data about the selected patient" or breaking down the FHIR resource types from the request scopes.

**Comment by vlad-ignatov** [comment]
Yes, some of those labels wording can be improved. Currently we have:
- `launch` -> `The current patient and encounter selection in the EHR system`
- `launch/patient` -> `The current patient selection`
- `launch/encounter` -> `The current encounter selection`

These could become:
- `launch` -> `All data about the selected patient and encounter`
- `launch/patient` -> `All data about the selected patient`
- `launch/encounter` -> `All data about the selected encounter`

@jmandel  I just want to clarify, what do you mean when you say `breaking down the FHIR resource types from the request scopes.`?

**Comment by jmandel** [comment]
The proposed updates look good!

By "breaking down the FHIR resource types from the request scopes" I meant handling a scope list with things like `patient/Observation.rs` and turning this into "see all Observations for the selected patient", and some behavior (even if it's just displaying them directly, or hard coding a couple of display names for the observation categories defined in US Core) for granular scopes like `patient/Observation.rs?category=http://terminology.hl7.org/CodeSystem/observation-category|laboratory`

**Comment by vlad-ignatov** [comment]
Ah, OK. That is a separate thing though.

Question: If I request `launch/patient patient/Observation.rs` what should I get access to - All data about the selected patient, or observations only?

The logic here was to handle the "global" scopes first (like the 3 listed above), and if they are not present to dig into more specific messages...

**Comment by jmandel** [comment]
Question: If I request `launch/patient patient/Observation.rs` what should I get access to

Technical answer: the id of the selected patient, and all observations about the selected patient

User language more like "All observations about the selected patient"

**Comment by vlad-ignatov** [comment]
- Added and prettified Gino's V2 scope parsing
- Removed the read/write/other grouping since it does not make a lot of sense with V2

Example:
<img width="973" alt="Screen Shot 2022-10-19 at 1 55 36 PM" src="https://user-images.githubusercontent.com/1119082/196769229-26c07048-6796-48b0-b0e5-d9e27505df0f.png">
